### ISSUE TITLE
构建失败，jenkins控制台报错显示：Failed to parse yaml

### ISSUE THREAD

**Issue by Linwenqiang-git** [go-atomci/atomci#194]
### 运行环境
* `应用版本`:
     * `atomci-frontend`: 基于v2.0-alpha分支本地运行
     * `atomci`: 基于v2.0-alpha分支本地运行
* `Kubernetes`: v1.21.6

#### 按照如下步骤，环境均已配置完成：
系统基础配置
	->服务集成（K8s、harbor、jenkins）
	->编译环境
	->代码源集成（github、gitee、gitlab）
	
创建应用（具体的服务）
	-> 选择代码源（系统配置的代码源）
	-> 仓库路径
	-> 编译环境

创建项目
	-> 项目环境（dev、test、online）
	-> 项目流程（构建、部署、人工卡点）
	-> 关联代码仓库（选择已创建好的应用）
	-> 应用编排
	-> 创建流水线
		-> 选择流程
		-> 选择分支
	-> 构建部署
		-> jenkins拉取构建服务
		-> 部署到K8s
jenkins与K8s可正确连接，且K8s相关插件正确安装
测试过两个场景，报错一致：
第一种：编排文件按照视频用官网默认的；
第二种：不填写编排文件；
构建均失败，jenkins控制台报错如下：
Started by user [administrators](http://192.168.79.137:8080/user/admin)
[Pipeline] Start of Pipeline
[Pipeline] podTemplate
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
hudson.remoting.ProxyException: io.fabric8.kubernetes.client.KubernetesClientException: name not specified for an operation requiring one.
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.requireFromServer(BaseOperation.java:182)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:142)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:93)
	at org.csanchez.jenkins.plugins.kubernetes.PodTemplateUtils.parseFromYaml(PodTemplateUtils.java:610)
	at org.csanchez.jenkins.plugins.kubernetes.PodTemplateUtils.validateYamlContainerNames(PodTemplateUtils.java:639)
	at org.csanchez.jenkins.plugins.kubernetes.PodTemplateUtils.validateYamlContainerNames(PodTemplateUtils.java:629)
	at org.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution.start(PodTemplateStepExecution.java:145)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:322)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:196)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:124)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
Caused: hudson.remoting.ProxyException: java.lang.RuntimeException: Failed to parse yaml: "
apiVersion: v1
kind: Pod
metadata:
  namespace: devops
spec:
  containers:
  - name: jnlp
    image: colynn/jenkins-jnlp-agent:latest
    workingDir: /home/jenkins/agent
    command:
    args:
    tty: true
  - name: kaniko
    image: colynn/kaniko-executor:debug
    workingDir: /home/jenkins/agent
    command:
    - /bin/sh
    - -c
    args:
    - cat
    tty: true
"
	at org.csanchez.jenkins.plugins.kubernetes.PodTemplateUtils.parseFromYaml(PodTemplateUtils.java:612)
	at org.csanchez.jenkins.plugins.kubernetes.PodTemplateUtils.validateYamlContainerNames(PodTemplateUtils.java:639)
	at org.csanchez.jenkins.plugins.kubernetes.PodTemplateUtils.validateYamlContainerNames(PodTemplateUtils.java:629)
	at org.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution.start(PodTemplateStepExecution.java:145)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:322)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:196)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:124)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at org.csanchez.jenkins.plugins.kubernetes.pipeline.KubernetesDeclarativeAgentScript.run(KubernetesDeclarativeAgentScript.groovy:51)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.inDeclarativeAgent(ModelInterpreter.groovy:594)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.call(ModelInterpreter.groovy:76)
	at WorkflowScript.run(WorkflowScript:3)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:90)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:116)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:85)
	at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ClosureBlock.eval(ClosureBlock.java:46)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:158)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:152)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:152)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:187)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:420)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:95)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:330)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:294)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Finished: FAILURE

### 截图
截图一直上传失败，直接复制了控制台信息

**Comment by colynn** [comment]
添加下『项目流程』包含哪些阶段， 及关联的任务模板的配置

**Comment by Linwenqiang-git** [comment]
任务模板采用的系统默认的：应用构建->应用部署->人工卡点
![image](https://github.com/go-atomci/atomci/assets/26178847/0d77d37d-963a-46aa-8a80-58edfa93ed9c)
目前在第一个阶段，应用构建出现上述问题
![image](https://github.com/go-atomci/atomci/assets/26178847/bee034db-c60f-478e-b42b-797b2937644f)

**Comment by colynn** [comment]
类似下图，你添加下关联应用的编译环境 再试下
<img width="952" alt="image" src="https://github.com/go-atomci/atomci/assets/5203608/f1dc1dc3-8907-491f-ad89-8643c9579e5e">

上图编译环境的来源是这里
<img width="1384" alt="image" src="https://github.com/go-atomci/atomci/assets/5203608/b9770c99-09fc-4778-8fb7-5d3c9395dab5">

**Comment by Linwenqiang-git** [comment]
> 类似下图，你添加下关联应用的编译环境 再试下 <img alt="image" width="952" src="https://user-images.githubusercontent.com/5203608/237266985-f1dc1dc3-8907-491f-ad89-8643c9579e5e.png">
> 
> 上图编译环境的来源是这里 <img alt="image" width="1384" src="https://user-images.githubusercontent.com/5203608/237267208-b9770c99-09fc-4778-8fb7-5d3c9395dab5.png">

![image](https://github.com/go-atomci/atomci/assets/26178847/7b5feb28-c799-4d22-b540-2f903ca3c6e7)
不行，还是和上面一样的报错

**Comment by colynn** [comment]
> 

系统管理 下的编译环境的设置是正常的吗

**Comment by Linwenqiang-git** [comment]
> > 
> 
> 系统管理 下的 选择的编译环境的详情麻烦也发出来看下
都是默认的，没有修改过，麻烦在帮忙看下

![image](https://github.com/go-atomci/atomci/assets/26178847/aaff85fd-29dd-4577-ab0b-8e4b14a9aa6b)
![image](https://github.com/go-atomci/atomci/assets/26178847/f8552cdb-8d64-42fc-af06-31cbbdf9ca8c)
![image](https://github.com/go-atomci/atomci/assets/26178847/53d97304-3003-4dea-a8d3-125e4f484b64)
![image](https://github.com/go-atomci/atomci/assets/26178847/77c96699-9164-47e0-bec0-4eec096f27a2)
![image](https://github.com/go-atomci/atomci/assets/26178847/b4ca4394-6744-401d-b13c-e7478c256da5)

**Comment by Linwenqiang-git** [comment]
![image](https://github.com/go-atomci/atomci/assets/26178847/1cd0c8b5-111f-43d4-a677-06cbacb344c2)
![image](https://github.com/go-atomci/atomci/assets/26178847/1c04b54e-6a8b-4f90-a9cb-2c3eea456172)
找了下源码，K8s Yaml文件的containers节点应该是不允许有重复Key的，
麻烦确认一下这是否是个bug

**Comment by colynn** [comment]
逻辑上 `name`前有 `-` 表示为两个条目，

**Comment by Linwenqiang-git** [comment]
> 逻辑上 `name`前有 `-` 表示为两个条目，

那会跟K8s插件版本之类的有关系吗？
目前整体流程还没跑通，个人感觉依赖jenkins过重，能否替换成一个具备构建环境的容器来代替？
yaml文件需要自己编写，有些繁琐。
还会持续关注，有机会希望也能够参与进来

**Comment by colynn** [comment]
你可以确认下 对应生成jenkins的 pipeline的代码 是否符合预期，如果符合预期那就有可能是kubernetes插件版本不一致导致的问题，

另外v1.0 重度依赖jenkins,  v2.0会引入 argo-workflow

**Comment by colynn** [comment]
> > 逻辑上 `name`前有 `-` 表示为两个条目，
> 
> 那会跟K8s插件版本之类的有关系吗？ 目前整体流程还没跑通，个人感觉依赖jenkins过重，能否替换成一个具备构建环境的容器来代替？ yaml文件需要自己编写，有些繁琐。 还会持续关注，有机会希望也能够参与进来

使用的jenkins是哪个版本？我复现下问题

**Comment by Linwenqiang-git** [comment]
> 

![image](https://github.com/go-atomci/atomci/assets/26178847/990347b5-caa6-49d9-91f0-94947812188b)

**Comment by colynn** [comment]
@Linwenqiang-git  please confirm if can we close this issue.
